alias: Check when Laundry Done
description: ''
trigger:
  - platform: time_pattern
    minutes: /10
condition:
  - condition: state
    entity_id: input_boolean.laundrydone
    state: 'on'
  - condition: state
    entity_id: input_boolean.laundryinuse
    state: 'on'
action:
  - service: python_script.washer_done
    data: {}
mode: single
